//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace WindowsFormsApp1.inventario
{

    public partial class almacen : XPLiteObject
    {
        uint fidAlmacen;
        [Key]
        public uint idAlmacen
        {
            get { return fidAlmacen; }
            set { SetPropertyValue<uint>(nameof(idAlmacen), ref fidAlmacen, value); }
        }
        sucursales fidSucursal;
        [Association(@"almacenReferencessucursales")]
        public sucursales idSucursal
        {
            get { return fidSucursal; }
            set { SetPropertyValue<sucursales>(nameof(idSucursal), ref fidSucursal, value); }
        }
        productos fidProducto;
        [Association(@"almacenReferencesproductos")]
        public productos idProducto
        {
            get { return fidProducto; }
            set { SetPropertyValue<productos>(nameof(idProducto), ref fidProducto, value); }
        }
        uint fcantidadAlmacen;
        [ColumnDefaultValue(0)]
        public uint cantidadAlmacen
        {
            get { return fcantidadAlmacen; }
            set { SetPropertyValue<uint>(nameof(cantidadAlmacen), ref fcantidadAlmacen, value); }
        }
        uint fcantidadConsumo;
        [ColumnDefaultValue(0)]
        public uint cantidadConsumo
        {
            get { return fcantidadConsumo; }
            set { SetPropertyValue<uint>(nameof(cantidadConsumo), ref fcantidadConsumo, value); }
        }
    }

}
