//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace WindowsFormsApp1.inventario
{

    public partial class productos : XPLiteObject
    {
        uint fidProducto;
        [Key]
        public uint idProducto
        {
            get { return fidProducto; }
            set { SetPropertyValue<uint>(nameof(idProducto), ref fidProducto, value); }
        }
        categorias fidCategoria;
        [Association(@"productosReferencescategorias")]
        public categorias idCategoria
        {
            get { return fidCategoria; }
            set { SetPropertyValue<categorias>(nameof(idCategoria), ref fidCategoria, value); }
        }
        string fnombre;
        [Size(50)]
        public string nombre
        {
            get { return fnombre; }
            set { SetPropertyValue<string>(nameof(nombre), ref fnombre, value); }
        }
        string fdescripcion;
        [Size(50)]
        public string descripcion
        {
            get { return fdescripcion; }
            set { SetPropertyValue<string>(nameof(descripcion), ref fdescripcion, value); }
        }
        string fcodigo;
        [Indexed(Name = @"codigo", Unique = true)]
        [Size(20)]
        public string codigo
        {
            get { return fcodigo; }
            set { SetPropertyValue<string>(nameof(codigo), ref fcodigo, value); }
        }
        uint fminimo;
        public uint minimo
        {
            get { return fminimo; }
            set { SetPropertyValue<uint>(nameof(minimo), ref fminimo, value); }
        }
        bool fesBasico;
        public bool esBasico
        {
            get { return fesBasico; }
            set { SetPropertyValue<bool>(nameof(esBasico), ref fesBasico, value); }
        }
        [Association(@"almacenReferencesproductos")]
        public XPCollection<almacen> almacens { get { return GetCollection<almacen>(nameof(almacens)); } }
    }

}
