//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace WindowsFormsApp1.inventario
{

    public partial class sucursales : XPLiteObject
    {
        uint fidSucursal;
        [Key]
        public uint idSucursal
        {
            get { return fidSucursal; }
            set { SetPropertyValue<uint>(nameof(idSucursal), ref fidSucursal, value); }
        }
        string fplaza;
        [Indexed(Name = @"plaza", Unique = true)]
        [Size(30)]
        public string plaza
        {
            get { return fplaza; }
            set { SetPropertyValue<string>(nameof(plaza), ref fplaza, value); }
        }
        string fciudad;
        [Size(30)]
        public string ciudad
        {
            get { return fciudad; }
            set { SetPropertyValue<string>(nameof(ciudad), ref fciudad, value); }
        }
        [Association(@"almacenReferencessucursales")]
        public XPCollection<almacen> almacens { get { return GetCollection<almacen>(nameof(almacens)); } }
        [Association(@"tecnicasReferencessucursales")]
        public XPCollection<tecnicas> tecnicasCollection { get { return GetCollection<tecnicas>(nameof(tecnicasCollection)); } }
        [Association(@"usuariosReferencessucursales")]
        public XPCollection<usuarios> usuariosCollection { get { return GetCollection<usuarios>(nameof(usuariosCollection)); } }
    }

}
