//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace WindowsFormsApp1.inventario
{

    public partial class tecnicas : XPLiteObject
    {
        uint fidTecnica;
        [Key]
        public uint idTecnica
        {
            get { return fidTecnica; }
            set { SetPropertyValue<uint>(nameof(idTecnica), ref fidTecnica, value); }
        }
        sucursales fidSucursal;
        [Association(@"tecnicasReferencessucursales")]
        public sucursales idSucursal
        {
            get { return fidSucursal; }
            set { SetPropertyValue<sucursales>(nameof(idSucursal), ref fidSucursal, value); }
        }
        string fnombre;
        [Size(50)]
        public string nombre
        {
            get { return fnombre; }
            set { SetPropertyValue<string>(nameof(nombre), ref fnombre, value); }
        }
        string fapellido;
        [Size(50)]
        public string apellido
        {
            get { return fapellido; }
            set { SetPropertyValue<string>(nameof(apellido), ref fapellido, value); }
        }
    }

}
