//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace WindowsFormsApp1.inventario
{

    public partial class usuarios : XPLiteObject
    {
        uint fidUsuario;
        [Key]
        public uint idUsuario
        {
            get { return fidUsuario; }
            set { SetPropertyValue<uint>(nameof(idUsuario), ref fidUsuario, value); }
        }
        sucursales fidSucursal;
        [Association(@"usuariosReferencessucursales")]
        public sucursales idSucursal
        {
            get { return fidSucursal; }
            set { SetPropertyValue<sucursales>(nameof(idSucursal), ref fidSucursal, value); }
        }
        string fusername;
        [Indexed(Name = @"username", Unique = true)]
        [Size(20)]
        public string username
        {
            get { return fusername; }
            set { SetPropertyValue<string>(nameof(username), ref fusername, value); }
        }
        string fpassword;
        [Size(255)]
        public string password
        {
            get { return fpassword; }
            set { SetPropertyValue<string>(nameof(password), ref fpassword, value); }
        }
        uint fpermisos;
        public uint permisos
        {
            get { return fpermisos; }
            set { SetPropertyValue<uint>(nameof(permisos), ref fpermisos, value); }
        }
        string fnombre;
        [Size(50)]
        public string nombre
        {
            get { return fnombre; }
            set { SetPropertyValue<string>(nameof(nombre), ref fnombre, value); }
        }
        string fapellido;
        [Size(50)]
        public string apellido
        {
            get { return fapellido; }
            set { SetPropertyValue<string>(nameof(apellido), ref fapellido, value); }
        }
        bool fstatus;
        [ColumnDefaultValue(false)]
        public bool status
        {
            get { return fstatus; }
            set { SetPropertyValue<bool>(nameof(status), ref fstatus, value); }
        }
    }

}
